### ISSUE TITLE
Fix the triggers.tekton.dev/release labels in releases

### ISSUE THREAD

**Issue by nikhil-thomas** [openshift/tektoncd-triggers#126]
At present the `triggers.tekton.dev/release: "devel"` is not correctly formed in midstream releases.

We need to update the `generate-release.sh` script https://github.com/openshift/tektoncd-triggers/blob/master/openshift/release/generate-release.sh

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-triggers-controller
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: tekton-triggers
    app.kubernetes.io/component: controller
    # tekton.dev/release value replaced with inputs.params.versionTag in triggers/tekton/publish.yaml
    triggers.tekton.dev/release: "devel"
```

Ref: update in midstream Pipelines: 
**Reflect Tekton release version in Artifacts after release** https://github.com/openshift/tektoncd-pipeline/pull/323
