### ISSUE TITLE
Fix tektoncd-triggers/openshift/release/generate-release.sh to remove extra spaces in release manifest

### ISSUE THREAD

**Issue by nikhil-thomas** [openshift/tektoncd-triggers#91]
At present the manifest has an extra space each in `spec.image` which causes lint errors in tekton-operator-ci.

here
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-triggers-controller
...
      - name: tekton-triggers-controller
           image:  quay.io/openshift-pipeline/tektoncd-triggers-controller:v0.3.1
```
and here
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-triggers-webhook
...
      - name: tekton-triggers-controller
           image:  quay.io/openshift-pipeline/tektoncd-triggers-webhook:v0.3.1
```

This has happened with downstream pipeline release script as well.
https://github.com/openshift/tektoncd-pipeline-operator/pull/265
